# Debug logging for native troubleshooting
logging.level.org.springframework=INFO
logging.level.com.zaxxer.hikari=INFO
logging.level.org.mariadb.jdbc=INFO
firebase.service-account-file=${FIREBASE_SERVICE_ACCOUNT_FILE:${GOOGLE_APPLICATION_CREDENTIALS}}
spring.main.banner-mode=off
spring.threads.virtual.enabled=true
server.port=${SERVER_PORT}

# Polling frequency in milliseconds
movie.polling.fixed-rate-ms=60000

# Database Configuration
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Native image specific
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
